//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeterReadingsBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeterReadingsBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Джоба завершилась: {JobName} с ошибкой..
        /// </summary>
        internal static string StrFmtErrorJobEndedWithError {
            get {
                return ResourceManager.GetString("StrFmtErrorJobEndedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling failed with exception: {Exception}..
        /// </summary>
        internal static string StrFmtErrorPollingServiceFailed {
            get {
                return ResourceManager.GetString("StrFmtErrorPollingServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылка пользователю {UserChatId} закончилась с ошибкой..
        /// </summary>
        internal static string StrFmtErrorPromotionToUserFailed {
            get {
                return ResourceManager.GetString("StrFmtErrorPromotionToUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка джобы: {JobName} завершилась успешно..
        /// </summary>
        internal static string StrFmtInfoJobEndedSuccessful {
            get {
                return ResourceManager.GetString("StrFmtInfoJobEndedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка джобы: {JobName} запустилась..
        /// </summary>
        internal static string StrFmtInfoJobProcessStarted {
            get {
                return ResourceManager.GetString("StrFmtInfoJobProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting polling service..
        /// </summary>
        internal static string StrFmtInfoPollingServiceStarted {
            get {
                return ResourceManager.GetString("StrFmtInfoPollingServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылка: {PromotionName} удачно дошла до {CountUsers} клиентов..
        /// </summary>
        internal static string StrFmtInfoPromotionEndedSuccessful {
            get {
                return ResourceManager.GetString("StrFmtInfoPromotionEndedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запущена рассылка: {PromotionName} клиентам в количестве: {CountUsers}..
        /// </summary>
        internal static string StrFmtInfoPromotionStarted {
            get {
                return ResourceManager.GetString("StrFmtInfoPromotionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start receiving updates for {BotName}..
        /// </summary>
        internal static string StrFmtInfoStartReceiveingUpdates {
            get {
                return ResourceManager.GetString("StrFmtInfoStartReceiveingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждое 24 число месяца, в 12:00 по МСК..
        /// </summary>
        internal static string StrFmtInfoWaterReadingsEndPromotionJobDescription {
            get {
                return ResourceManager.GetString("StrFmtInfoWaterReadingsEndPromotionJobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждое 15 число месяца, в 12:00 по МСК..
        /// </summary>
        internal static string StrFmtInfoWaterReadingsStartPromotionJobDescription {
            get {
                return ResourceManager.GetString("StrFmtInfoWaterReadingsStartPromotionJobDescription", resourceCulture);
            }
        }
    }
}
